// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uzrkeuweietxkwubhbym.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV6cmtldXdlaWV0eGt3dWJoYnltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg3NzU3MDMsImV4cCI6MjA4NDM1MTcwM30.gs9xYrFUdnFJnBGmfrJv2vlwsI8hWCjwjbUJhJRlF9g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});